@startuml
component schema_generator
component md_tables_generator
component profile_validator
component pandoc

artifact netex.xsd
artifact profile.xsd
artifact profile_spec.xml
artifact profile.sch
artifact skeleton_stylesheet
artifact report.svrl
artifact ch_netex.xml
artifact tables.md
artifact netex_rg.doc
artifact netex_rg.md

ch_netex.xml <-- profile_validator : validates
skeleton_stylesheet <-- profile_validator : uses
profile.sch <-- profile_validator : applies
profile_validator --> report.svrl : creates
profile_spec.xml --> schema_generator
profile_spec.xml --> profile.sch
schema_generator --> profile.xsd
netex_rg.md --> tables.md : includes
netex_rg.doc <-- pandoc : converts from
pandoc --> netex_rg.md : converts to
profile.xsd --> md_tables_generator
md_tables_generator --> tables.md
netex.xsd <-- profile_spec.xml : refers to

note right of ch_netex.xml
NeTEx example documents
end note

note right of profile_spec.xml
Variants:
- Example/Template
- Schematron
- XML Document
end note

note right of schema_generator
Variants:
- Python script
- Stylesheet
end note

note right of profile.sch
Schematron rules
end note

note right of md_tables_generator
Variants:
- xcore adapted to NeTEx
- Python script
end note

note right of pandoc
run once
end note

note left of netex_rg.md
- edited manually
- main file includes multiple other files
end note

note right of tables.md
- multiple files
- hierarchy:
  namespace/types/StopPlaceType.md
  namespace/elements/StopPlace.md
  namespace/groups/...
end note

@enduml